version: '3'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=80.225.209.180
      - LETSENCRYPT_HOST=80.225.209.180