version: '3'
services:
  go-web-app:
    container_name: allcoaching_go
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=155.248.254.181
      - LETSENCRYPT_HOST=155.248.254.181